version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" 
    ports:
      - '4306:3306'
  php:
    image: aidarms/freelancemarket
    container_name: freelancemarket
    volumes: 
     - ".env:/app/.env"
    ports:
      - '8000:80'
    links: 
      - mysql
    